FROM python:3.10-slim

WORKDIR /app

COPY requirements-streamlit.txt .
RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY streamlit_app/ ./streamlit_app/

EXPOSE 7860

CMD streamlit run streamlit_app/app.py --server.port=${PORT:-7860} --server.address=0.0.0.0
